### ISSUE TITLE
allow exporting an async function for config

### ISSUE THREAD

**Issue by sachinraja** [contentlayerdev/contentlayer#15]
I want to use [`shiki`](https://github.com/shikijs/shiki) for syntax highlighting, but its `getHighlighter` function is async. Since top-level await is not implemented in esbuild, it is not possible for me to export an object for the config. If an async function was accepted, I could get the highlighter and return the config.

**Comment by schickling** [comment]
This should already be possible as seen in this example:

https://github.com/contentlayerdev/contentlayer/blob/1f206e4e0f21a51875f39b7a83f9956f53ef0607/examples/gatsby-docs/contentlayer.config.ts#L57-L76

However AFAIK using `shiki` is currently blocked due to `rehype-shiki` [not supporting unified v10 yet](https://github.com/leafac/rehype-shiki/issues/2). But the original issue about being able to use `async` / `await` within `makeSource` should be already sufficiently addressed, no?

Please let me know if you need further help :)

**Comment by sachinraja** [comment]
Thanks! The issue was I was wrapping the returned object in `makeSource` instead of the function. I am getting another error now, with `@stefanprobst/remark-shiki` (which is on `unified` 10):
```
> _mdx_bundler_entry_point-b14f587e-98f9-46bf-acd9-f5b974580967.mdx:0:0: error: [plugin: esbuild-xdm] 
    0 │ 
      ╵ ^

Error: Found problems in 1 of 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "blog/typescript-adventures.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     _mdx_bundler_entry_point-b14f587e-98f9-46bf-acd9-f5b974580967.mdx:0:0: error: [plugin: esbuild-xdm]
```
Not sure if it has to do with this, but I'm passing options to it:
```ts
{
    contentDirPath: 'data',
    documentTypes: [Post],
    mdx: {
      remarkPlugins: [remarkGfm, [remarkShiki, { highlighter }]],
    },
  }
```

**Comment by schickling** [comment]
I'm sorry for this unhelpful error message. This is most likely due to the error handling in `mdx-bundler` (see [this issue](https://github.com/kentcdodds/mdx-bundler/issues/117)).

Happy to help you debug this further (probably the quickest way is [in our Discord](https://discord.gg/fk83HNECYJ)).
