### ISSUE TITLE
Parsing failed

### ISSUE THREAD

**Issue by Manubi** [contentlayerdev/contentlayer#272]
Hi,
First of all thanks for the work, I really like the idea behind contentlayer.
```
"next": "12.2.2",
"next-contentlayer": "^0.2.6",
"contentlayer": "^0.2.6",
```

<img width="1786" alt="CleanShot 2022-07-19 at 10 57 15@2x" src="https://user-images.githubusercontent.com/20935138/179711170-df4aa4e9-049c-404b-9bf9-1ec363c248c7.png">

I don't really know how I can start debugging the error. 

Any help is appreciated. 

Thanks!

**Comment by stefanprobst** [comment]
i think this is just a webpack warning and can be ignored. if it's too annoying it can be silenced by setting [this](https://webpack.js.org/configuration/other-options/#level) in webpack config to `error`.

**Comment by schickling** [comment]
Thanks for opening this issue @Manubi. Unfortunately this is an upstream issue in Next / Webpack (see https://github.com/webpack/webpack/pull/15688) that currently occurs when you're using `next.config.mjs` (instead of `next.config.js`). These warnings shouldn't cause any problems in terms of functionality but are obviously rather annoying. I hope this gets fixed in Webpack soon. 😇
