### ISSUE TITLE
Getting Socket.dev warnings for contentlayer 0.3.3

### ISSUE THREAD

**Issue by steven-tey** [contentlayerdev/contentlayer#484]
Absolutely love the package, fantastic work @schickling!

I'm getting a warning from socket.dev for the latest version of contentlayer (0.3.3) because of the postinstall script: https://github.com/steven-tey/dub/pull/234/checks?check_run_id=14138228122

![CleanShot 2023-06-09 at 09 17 42](https://github.com/contentlayerdev/contentlayer/assets/28986134/1eaebc64-d06c-497d-830b-171fcd4d9416)

I'm sure it's benign but just wanted to give you a headsup!

**Comment by schickling** [comment]
Thanks a lot for your kind words @steven-tey and for opening this issue. The two reported Socket "issues" are indeed benign:

- The `contentlayer` postinstall script tries to already generate types etc right after install to improve the DX
- The `protobufjs` postinstall is there because `protobufjs` is currently used for the Otel setup which is used during development. I could try to remove this from the prod builds if important to some users.

Is there anything actionable you'd hope for?
